<a href="https://colab.research.google.com/github/satyam-311/basic_chatbot/blob/main/pytorch_fundamentals00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Mon Jul 28 17:51:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch # Google Colab comes with torch already installed
print(torch.cuda.is_available()) # will return True if PyTorch can use the GPU
print(torch.__version__)

True
2.6.0+cu124


In [6]:
%pip install torchinfo

In [10]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

# Check for GPU (should return True)
print(torch.cuda.is_available())

tensor([[-0.9743,  0.5585,  0.3031],
        [ 0.3404,  0.5561, -0.4170],
        [-0.2031, -0.0055,  0.8179]])
True


In [11]:
!nvidia-smi

Mon Jul 28 18:51:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [12]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [13]:
vector=torch.tensor([7,3])
vector

tensor([7, 3])

In [14]:
vector.ndim

1

In [15]:
scalar.ndim

0

In [17]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
matrix.shape

torch.Size([2, 2])

In [19]:
matrix.ndim

2

In [20]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9291, 0.0083, 0.8332, 0.8079],
         [0.5808, 0.5268, 0.5320, 0.4587],
         [0.9097, 0.2365, 0.0137, 0.5173]]),
 torch.float32)

In [25]:
# Create a random tensor with a shape similar to an image (e.g., color channels, height, width)
random_image_tensor = torch.rand(size=(3, 256, 256))
print("Shape of the random image tensor:", random_image_tensor.shape)

Shape of the random image tensor: torch.Size([3, 256, 256])


In [ ]:
jj